#!/bin/bash
#SBATCH --partition=workq
#SBATCH --job-name="vasp"
#SBATCH --nodes=16
#SBATCH --time=4:00:00
#SBATCH --exclusive
#SBATCH --err=std.err
#SBATCH --output=std.out
#----------------------------------------------------------#
#export VASP_USE=""  # This is the default, compiled with ScaLAPACK
#export VASP_USE=_omp # The version compiled with ScaLAPACK and threaded MKL
#export VASP_USE=_nbo # http://schmidt.chem.wisc.edu/nbosoftware
#export VASP_USE=_vaspsol # http://vaspsol.mse.ufl.edu/
#export VASP_USE=_vtst178 # http://theory.cm.utexas.edu/vtsttools/
#export VASP_USE=_dftd4 # https://github.com/dftd4/dftd4_vasp
#export VASP_USE=_transopt # https://github.com/yangjio4849/TransOpt
#export VASP_USE=_z2pack # https://z2pack.greschd.ch/en/latest/tutorial/installation.html
#export VASP_USE=_libbeef # https://github.com/vossjo/libbeef
#export VASP_USE=_occmat # https://github.com/WatsonGroupTCD/Occupation-matrix-control-in-VASP
module load vasp/5.4.4
export OMP_NUM_THREADS=1
#----------------------------------------------------------#
echo "The job "${SLURM_JOB_ID}" is running on "${SLURM_JOB_NODELIST}
#----------------------------------------------------------#
srun --ntasks=512 --hint=nomultithread ${VASP_HOME}/vasp_std
