#!/bin/bash -e

# This scirpt load various modules into the project folder for computation
# Change this module directory for Q.E. LAMMPS VASP SIESTA accordingly
modueleDIR=/ibex/scratch/jangira/vasp/vasp-scripts/modules


# $projectDIR $initDIR $srcDIR $resultDIR $calcDIR
# Following variabels are generated by ./setGlobalVariable.sh
source ./setGlobalVariable.sh
mkdir -p $projectDIR $initDIR $srcDIR $resultDIR $calcDIR


modules=($(ls $modueleDIR/))        # creating list of available modules
len=${#modules[@]}                  # total no of modules
len=$(echo "$len - 1" | bc -lq)     # subtracting 1


# printing to prompt message and taking input
for i in $(seq 0 $len); do
    echo "$i : ${modules[$i]} module"
done
read -p "Input Selection : " module_ids


# copying and logging modules based on input
for id in $module_ids; do
    module_name=${modules[$id]}
    echo "Copying...${module_name}"
    cp -r $modueleDIR/${module_name} $srcDIR/
    echo "Copy done...${module_name}"
    if [ -f $modueleDIR/${module_name}/README.MD ]; then
        cat $modueleDIR/${module_name}/README.MD
    fi
    echo -e "\n---------><------------\n"
done
