#!/bin/bash
#SBATCH --partition=workq
#SBATCH --job-name="vasp"
#SBATCH --nodes=__nodes__
#SBATCH --time=24:00:00
#SBATCH --exclusive
#SBATCH --err=std.err
#SBATCH --output=std.out
#----------------------------------------------------------#
module load vasp/5.4.4
export OMP_NUM_THREADS=1
#----------------------------------------------------------#
echo "The job "${SLURM_JOB_ID}" is running on "${SLURM_JOB_NODELIST}
#----------------------------------------------------------#
srun --ntasks=__ntasks__ --hint=nomultithread ${VASP_HOME}/vasp_std
