name: lmp-vasp

channels:
  - defaults
  - conda-forge

dependencies:
  - python=2
  - pip
  - autopep8
  # - py4vasp
  # - numpy
  # - scipy
  # - pandas
  # - ase
  # - shapely
  # - matplotlib
  # - jupyterlab
  # - jupyterlab-lsp

# phonopy
  - conda-forge::phonopy

